services:
  bot:
    image: blundering-savant:latest
    container_name: blundering-savant-bot
    restart: unless-stopped
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - CHECK_INTERVAL=${CHECK_INTERVAL:-5m}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
