# Validation workflow specifically for the Blundering Savant bot
# This workflow includes automatic formatting commits for Go files

name: Blundering Savant Validate

on:
  push:
    branches: [ "wip/issue-86-as-part-of-validation,-execute-gofmt-on-changed-files" ]
  workflow_dispatch:

jobs:

  build-lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.4'

    - name: Format Go files
      run: |
        # Format all Go files
        gofmt -w .
        
        # Check if any files were changed by gofmt
        if [ -n "$(git status --porcelain)" ]; then
          echo "Files were formatted, committing changes..."
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto-format Go files with gofmt"
          git push
        else
          echo "No formatting changes needed"
        fi

    - name: Build
      run: go build -v ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v8.0.0
      with:
        version: v2.3

    - name: Format check
      run: |
        if [ -n "$(gofmt -l .)" ]; then
          echo "The following files are not properly formatted:"
          gofmt -l .
          exit 1
        fi

    - name: Test
      run: go test -v ./...