# Validation workflow specifically for the Blundering Savant bot
# This workflow includes automatic formatting commits for Go files

name: Blundering Savant Validate

on:
  workflow_dispatch:

jobs:

  build-lint-test:
    permissions:
      contents: write # To commit gofmt changes

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.4'

    - name: Tidy changes
      run: |
        # Format all Go files
        gofmt -w .

        # Clean up dependencies
        go mod tidy

        # Check if any files were changed
        if [ -n "$(git status --porcelain)" ]; then
          echo "Files were updated, committing changes..."
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto-format Go files and tidy dependencies"
          git push
        else
          echo "No changes needed"
        fi

    - name: Build
      run: go build -v ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v8.0.0
      with:
        version: v2.3

    - name: Format check
      run: |
        if [ -n "$(gofmt -l .)" ]; then
          echo "The following files are not properly formatted:"
          gofmt -l .
          exit 1
        fi

    - name: Test
      run: go test -v ./...