name: Bot Runner
on:
  issues:
    types: [assigned, labeled]
  issue_comment:
    types: [created]
  pull_request:
    types: [synchronize]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]

jobs:
  run:
    permissions:
      actions: write        # To create workflow dispatch events
      contents: write       # To make code changes
      issues: write         # To edit labels and comment on issues
      pull-requests: write  # To edit labels and comment on pull requests

    runs-on: ubuntu-latest

    # Run if the triggering user is the authorized user configured for the repository AND:
    # - The affected issue is assigned to the bot, OR
    # - The affected pull request is owned by the bot, OR
    if: >
      github.actor == vars.AUTHORIZED_USERNAME &&
      (
        (github.event.issue && github.event.issue.assignee.login == vars.BOT_USERNAME) ||
        (github.event.pull_request && github.event.pull_request.user.login == vars.BOT_USERNAME)
      )

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.4'

    - name: Build bot
      run: go build -o blundering-savant ./app/blundering-savant

    - name: Run bot
      timeout-minutes: 30
      env:
        SYSTEM_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        echo "Processing ${{ github.event_name }}.${{ github.event.action }} by ${{ github.actor }}"

        # Determine whether to use issue number or PR branch
        if [ -n "${{ github.event.issue.number }}" ]; then
          echo "Repository: ${{ github.repository }} / Issue #${{ github.event.issue.number }}"
          ./blundering-savant oneshot \
            --repo ${{ github.repository }} \
            --issue ${{ github.event.issue.number }} \
            --validation-workflow go.yml
        elif [ -n "${{ github.event.pull_request.head.ref }}" ]; then
          echo "Repository: ${{ github.repository }} / PR branch '${{ github.event.pull_request.head.ref }}'"
          ./blundering-savant oneshot \
            --repo ${{ github.repository }} \
            --pr-branch ${{ github.event.pull_request.head.ref }} \
            --validation-workflow go.yml
        else
          echo "Error: Neither issue number nor PR branch available"
          exit 1
        fi

        if [ $? -ne 0 ]; then
          echo "Bot failed with exit code $?"
          exit 1
        fi

        echo "Bot completed successfully"

    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: bot-logs-${{ github.run_id }}
        path: logs/
        retention-days: 7