# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.4'

    - name: Build
      run: go build -v ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v8.0.0
      with:
        version: v2.3

    - name: Format check
      run: |
        if [ -n "$(gofmt -l .)" ]; then
          echo "The following files are not properly formatted:"
          gofmt -l .
          exit 1
        fi

    - name: Test
      run: go test -v ./...
